### PR TITLE
skip bias subtraction when bias already subtracted

### PR DESCRIPTION
**Pull request by jchate6**
If the header reports that the bias has already been removed, we don't do it again.
Also fixing a few typos....

### CODE REVIEW

**Comment by jchate6** [comment]
I tested this locally with a few defocused but reduced sinistro images and a defocused but unreduced sbig image. 
It ran correctly, through the code concerned here, but didn't fully complete (I suspect because I only used 1 or 2 images each and couldn't complete the quiver plot).

**Review by emannenicholas — APPROVED** [review]
lgtm

**Review by cmccully — CHANGES_REQUESTED** [review]
This code doesn't do what you think it's doing.

**Comment by jchate6** [comment]
See PR #22

**Pull request closed without merging**
